### ISSUE TITLE
Book view page

### ISSUE THREAD

**Issue by AudioManiac-coder** [HermanFassett/cleanreads-extension#1]
Extension stopped working book view page after new layout was released. Any plans to update?

E.g. `https://www.goodreads.com/book/show/60415700-now-is-not-the-time-to-panic`

**Comment by HermanFassett** [comment]
I do plan to update, I've been drafting changes, but it's hard to finalize a new version until they finish rolling out the new book page. I still see old book page in my primary browser and the way Cleanreads loads data behind the scenes seems to always get old book page as well. 
I can try to push an intermediary update, but it would probably stop working once they finish rolling out the update.

**Comment by AudioManiac-coder** [comment]
Well damn, I didn't even realize it's not yet released globally. Librarians were part of the test group for so long that when they forced enabled it I thought it was global. I contacted them about re-design and they have no idea when they going to finalize it, so far book page is the only one they did any testing in public. 

I would love the intermediary update as this became a mandatory tool for me in choosing books. But I understand if you prefer to wait for things to settle down.

**Comment by HermanFassett** [comment]
Sounds good, I've pushed changes that I was sitting on and requested publish to web store, but I'm not sure it's totally working with new pages yet. I'll leave this issue open for further changes as the feature is finalized.

**Comment by AudioManiac-coder** [comment]
The extension stopped loading the ratings recently. Just stuck on `Loading...`. 
Errors from console
![image](https://user-images.githubusercontent.com/70440929/217115381-3b8f3570-4065-485a-87c9-7bc3a62018ef.png)

**Comment by HermanFassett** [comment]
Thanks @AudioManiac-coder, it looks like they've pushed the new book page to all readers which includes the headless lookup in the extension. I'll try to get an update working when I get a chance.

**Comment by HermanFassett** [comment]
This should be fixed, though I didn't test a lot. Please do report any new issues if you find some. I've merged changes and requested chrome web store publish.
